import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { Cell, CellStyles, Sheet } from '../../models/sheet.model';
import { SheetComponent } from '../sheet/sheet.component';

@Component({
  selector: 'sheet-container',
  standalone: true,
  imports: [CommonModule, SheetComponent],
  templateUrl: './sheet-container.component.html',
  // Notice the correct property name is styleUrls (plural), not styleUrl
  styleUrls: ['./sheet-container.component.scss']
})
export class SheetContainerComponent {
  private dummyCells: Cell[][] = [
    [
      new Cell('A1', { isReferenceCell: true }),
      new Cell('B1', { isReferenceCell: true }),
      new Cell('C1', { isReferenceCell: true }),
      new Cell('D1', { isReferenceCell: true }),
    ],
    [
      new Cell('A2'),
      new Cell('B2'),
      new Cell('C2'),
      new Cell('D2'),
    ],
    [
      new Cell('A3'),
      new Cell('B3'),
      new Cell('C3'),
      new Cell('D3'),
    ],
    [
      new Cell('A4'),
      new Cell('B4'),
      new Cell('C4'),
      new Cell('D4'),
    ],
    [
      new Cell('A1'),
      new Cell('B1'),
      new Cell('C1'),
      new Cell('D1'),
    ],
    [
      new Cell('A2'),
      new Cell('B2'),
      new Cell('C2'),
      new Cell('D2'),
    ],
    [
      new Cell('A3'),
      new Cell('B3'),
      new Cell('C3'),
      new Cell('D3'),
    ],
    [
      new Cell('A4'),
      new Cell('B4'),
      new Cell('C4'),
      new Cell('D4'),
    ],
    [
      new Cell('A1'),
      new Cell('B1'),
      new Cell('C1'),
      new Cell('D1'),
    ],
    [
      new Cell('A2'),
      new Cell('B2'),
      new Cell('C2'),
      new Cell('D2'),
    ],
    [
      new Cell('A3'),
      new Cell('B3'),
      new Cell('C3'),
      new Cell('D3'),
    ],
    [
      new Cell('A4'),
      new Cell('B4'),
      new Cell('C4'),
      new Cell('D4'),
    ],
    [
      new Cell('A1'),
      new Cell('B1'),
      new Cell('C1'),
      new Cell('D1'),
    ],
    [
      new Cell('A2'),
      new Cell('B2'),
      new Cell('C2'),
      new Cell('D2'),
    ],
    [
      new Cell('A3'),
      new Cell('B3'),
      new Cell('C3'),
      new Cell('D3'),
    ],
    [
      new Cell('A4'),
      new Cell('B4'),
      new Cell('C4'),
      new Cell('D4'),
    ],
    [
      new Cell('A1'),
      new Cell('B1'),
      new Cell('C1'),
      new Cell('D1'),
    ],
    [
      new Cell('A2'),
      new Cell('B2'),
      new Cell('C2'),
      new Cell('D2'),
    ],
    [
      new Cell('A3'),
      new Cell('B3'),
      new Cell('C3'),
      new Cell('D3'),
    ],
    [
      new Cell('A4'),
      new Cell('B4'),
      new Cell('C4'),
      new Cell('D4'),
    ],
    [
      new Cell('A1'),
      new Cell('B1'),
      new Cell('C1'),
      new Cell('D1'),
    ],
    [
      new Cell('A2'),
      new Cell('B2'),
      new Cell('C2'),
      new Cell('D2'),
    ],
    [
      new Cell('A3'),
      new Cell('B3'),
      new Cell('C3'),
      new Cell('D3'),
    ],
    [
      new Cell('A4'),
      new Cell('B4'),
      new Cell('C4'),
      new Cell('D4'),
    ],
    [
      new Cell('A1'),
      new Cell('B1'),
      new Cell('C1'),
      new Cell('D1'),
    ],
    [
      new Cell('A2'),
      new Cell('B2'),
      new Cell('C2'),
      new Cell('D2'),
    ],
    [
      new Cell('A3'),
      new Cell('B3'),
      new Cell('C3'),
      new Cell('D3'),
    ],
    [
      new Cell('A4'),
      new Cell('B4'),
      new Cell('C4'),
      new Cell('D4'),
    ],
    [
      new Cell('A1'),
      new Cell('B1'),
      new Cell('C1'),
      new Cell('D1'),
    ],
    [
      new Cell('A2'),
      new Cell('B2'),
      new Cell('C2'),
      new Cell('D2'),
    ],
    [
      new Cell('A3'),
      new Cell('B3'),
      new Cell('C3'),
      new Cell('D3'),
    ],
    [
      new Cell('A4'),
      new Cell('B4'),
      new Cell('C4'),
      new Cell('D4'),
    ],
    [
      new Cell('A1'),
      new Cell('B1'),
      new Cell('C1'),
      new Cell('D1'),
    ],
    [
      new Cell('A2'),
      new Cell('B2'),
      new Cell('C2'),
      new Cell('D2'),
    ],
    [
      new Cell('A3'),
      new Cell('B3'),
      new Cell('C3'),
      new Cell('D3'),
    ],
    [
      new Cell('A4'),
      new Cell('B4'),
      new Cell('C4'),
      new Cell('D4'),
    ],
    [
      new Cell('A1'),
      new Cell('B1'),
      new Cell('C1'),
      new Cell('D1'),
    ],
    [
      new Cell('A2'),
      new Cell('B2'),
      new Cell('C2'),
      new Cell('D2'),
    ],
    [
      new Cell('A3'),
      new Cell('B3'),
      new Cell('C3'),
      new Cell('D3'),
    ],
    [
      new Cell('A4'),
      new Cell('B4'),
      new Cell('C4'),
      new Cell('D4'),
    ],
    [
      new Cell('A1'),
      new Cell('B1'),
      new Cell('C1'),
      new Cell('D1'),
    ],
    [
      new Cell('A2'),
      new Cell('B2'),
      new Cell('C2'),
      new Cell('D2'),
    ],
    [
      new Cell('A3'),
      new Cell('B3'),
      new Cell('C3'),
      new Cell('D3'),
    ],
    [
      new Cell('A4'),
      new Cell('B4'),
      new Cell('C4'),
      new Cell('D4'),
    ],
    [
      new Cell('A1'),
      new Cell('B1'),
      new Cell('C1'),
      new Cell('D1'),
    ],
    [
      new Cell('A2'),
      new Cell('B2'),
      new Cell('C2'),
      new Cell('D2'),
    ],
    [
      new Cell('A3'),
      new Cell('B3'),
      new Cell('C3'),
      new Cell('D3'),
    ],
    [
      new Cell('A4'),
      new Cell('B4'),
      new Cell('C4'),
      new Cell('D4'),
    ],
    [
      new Cell('A1'),
      new Cell('B1'),
      new Cell('C1'),
      new Cell('D1'),
    ],
    [
      new Cell('A2'),
      new Cell('B2'),
      new Cell('C2'),
      new Cell('D2'),
    ],
    [
      new Cell('A3'),
      new Cell('B3'),
      new Cell('C3'),
      new Cell('D3'),
    ],
    [
      new Cell('A4'),
      new Cell('B4'),
      new Cell('C4'),
      new Cell('D4'),
    ],
    [
      new Cell('A1'),
      new Cell('B1'),
      new Cell('C1'),
      new Cell('D1'),
    ],
    [
      new Cell('A2'),
      new Cell('B2'),
      new Cell('C2'),
      new Cell('D2'),
    ],
    [
      new Cell('A3'),
      new Cell('B3'),
      new Cell('C3'),
      new Cell('D3'),
    ],
    [
      new Cell('A4'),
      new Cell('B4'),
      new Cell('C4'),
      new Cell('D4'),
    ],
    [
      new Cell('A1'),
      new Cell('B1'),
      new Cell('C1'),
      new Cell('D1'),
    ],
    [
      new Cell('A2'),
      new Cell('B2'),
      new Cell('C2'),
      new Cell('D2'),
    ],
    [
      new Cell('A3'),
      new Cell('B3'),
      new Cell('C3'),
      new Cell('D3'),
    ],
    [
      new Cell('A4'),
      new Cell('B4'),
      new Cell('C4'),
      new Cell('D4'),
    ],

  ];

  public dummySheet: Sheet = {
    cells: this.dummyCells,
    columns: [
      { width: 100, styles: new CellStyles() },
      { width: 100, styles: new CellStyles() },
      { width: 100, styles: new CellStyles() },
      { width: 100, styles: new CellStyles() },
    ],
    rows: [
      { height: 20, styles: new CellStyles() },
      { height: 20, styles: new CellStyles() },
      { height: 20, styles: new CellStyles() },
      { height: 20, styles: new CellStyles() },
      { height: 20, styles: new CellStyles() },
      { height: 20, styles: new CellStyles() },
      { height: 20, styles: new CellStyles() },
      { height: 20, styles: new CellStyles() },
      { height: 20, styles: new CellStyles() },
      { height: 20, styles: new CellStyles() },
      { height: 20, styles: new CellStyles() },
      { height: 20, styles: new CellStyles() },
      { height: 20, styles: new CellStyles() },
      { height: 20, styles: new CellStyles() },
      { height: 20, styles: new CellStyles() },
      { height: 20, styles: new CellStyles() },
      { height: 20, styles: new CellStyles() },
      { height: 20, styles: new CellStyles() },
      { height: 20, styles: new CellStyles() },
      { height: 20, styles: new CellStyles() },
      { height: 20, styles: new CellStyles() },
      { height: 20, styles: new CellStyles() },
      { height: 20, styles: new CellStyles() },
      { height: 20, styles: new CellStyles() },
      { height: 20, styles: new CellStyles() },
      { height: 20, styles: new CellStyles() },
      { height: 20, styles: new CellStyles() },
      { height: 20, styles: new CellStyles() },
      { height: 20, styles: new CellStyles() },
      { height: 20, styles: new CellStyles() },
      { height: 20, styles: new CellStyles() },
      { height: 20, styles: new CellStyles() },
      { height: 20, styles: new CellStyles() },
      { height: 20, styles: new CellStyles() },
      { height: 20, styles: new CellStyles() },
      { height: 20, styles: new CellStyles() },
      { height: 20, styles: new CellStyles() },
      { height: 20, styles: new CellStyles() },
      { height: 20, styles: new CellStyles() },
      { height: 20, styles: new CellStyles() },
      { height: 20, styles: new CellStyles() },
      { height: 20, styles: new CellStyles() },
      { height: 20, styles: new CellStyles() },
      { height: 20, styles: new CellStyles() },
      { height: 20, styles: new CellStyles() },
      { height: 20, styles: new CellStyles() },
      { height: 20, styles: new CellStyles() },
      { height: 20, styles: new CellStyles() },
      { height: 20, styles: new CellStyles() },
      { height: 20, styles: new CellStyles() },
      { height: 20, styles: new CellStyles() },
      { height: 20, styles: new CellStyles() },
      { height: 20, styles: new CellStyles() },
      { height: 20, styles: new CellStyles() },
      { height: 20, styles: new CellStyles() },
      { height: 20, styles: new CellStyles() },
      { height: 20, styles: new CellStyles() },
      { height: 20, styles: new CellStyles() },
      { height: 20, styles: new CellStyles() },
      { height: 20, styles: new CellStyles() },
    ],
  };
}
